// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsfVGwOyz2k_hxv4MtESuXI_mU-PhX5-4',
    appId: '1:252673283223:web:6a6de33ee6fd3fbf1ec5d2',
    messagingSenderId: '252673283223',
    projectId: 'disabled-people',
    authDomain: 'disabled-people.firebaseapp.com',
    storageBucket: 'disabled-people.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8HlfLPwZ8R57zikM6JPNT-QJTaBUkfwo',
    appId: '1:252673283223:android:b3003a9d2d29a5bc1ec5d2',
    messagingSenderId: '252673283223',
    projectId: 'disabled-people',
    storageBucket: 'disabled-people.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpuSkWrZnrjAgLhjGMMXJN_G_ow3n9yrA',
    appId: '1:252673283223:ios:f43a272d043c8acb1ec5d2',
    messagingSenderId: '252673283223',
    projectId: 'disabled-people',
    storageBucket: 'disabled-people.appspot.com',
    iosClientId: '252673283223-c3ajpca9amn129j8vll70ud7v03nqchm.apps.googleusercontent.com',
    iosBundleId: 'com.example.disaoledPeople',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpuSkWrZnrjAgLhjGMMXJN_G_ow3n9yrA',
    appId: '1:252673283223:ios:f43a272d043c8acb1ec5d2',
    messagingSenderId: '252673283223',
    projectId: 'disabled-people',
    storageBucket: 'disabled-people.appspot.com',
    iosClientId: '252673283223-c3ajpca9amn129j8vll70ud7v03nqchm.apps.googleusercontent.com',
    iosBundleId: 'com.example.disaoledPeople',
  );
}
